name: fluttersoundplayer
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter: ">=1.12.13+hotfix.6 <2.0.0"

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  assets_audio_player: ^2.0.13


flutter:

  uses-material-design: true

  assets:
    - assets/audios/
